export enum ConfigEnum {
  DB_TYPE = "DB_TYPE",
  DB_HOST = "DB_HOST",
  DB_PORT = "DB_PORT",
  DB_USERNAME = "DB_USERNAME",
  DB_PASSPORT = "DB_PASSPORT",
  DB_DATABASE = "DB_DATABASE",
  DB_SYNC = "DB_SYNC",
  DB_LOGGING = "DB_LOGGING"
}